#/control/execute visu.mac

/control/execute verbose.mac

/control/execute Geometry.mac

/gate/application/setTotalNumberOfPrimaries 10000

/gate/source/beam/gps/energytype Mono
/gate/source/beam/gps/monoenergy 127.2 MeV

/control/execute Sample.mac

/gate/actor/Range/save                         /media/sf_linux_share/Data/GATE_Simulations/RangeInWater/18112016/125MeV_Water_1.5cm_{mat}.txt
/gate/run/initialize
/gate/application/start
