#/control/execute visu.mac

/control/execute verbose.mac

/control/execute Geometry.mac

/control/execute Sample_RibBone.mac

/gate/actor/Range/save                         /media/sf_Desktop/250MeV_PhantomMaterials.txt
/gate/application/setTotalNumberOfPrimaries 100000
/gate/run/initialize
/gate/application/start

#/gate/geometry/setIonisationPotential PVC 352.18 eV
#/gate/actor/Range/save                          /media/sf_Desktop/stoppingpowers/PVC_I=352p18.txt
#/gate/run/initialize
#/gate/application/start

#/gate/geometry/setIonisationPotential PMMA 123 eV
#/gate/actor/Range/save                         /media/sf_Desktop/stoppingpowers/PMMA_RSP=1p09.txt
#/gate/run/initialize
#/gate/application/start
