# Visualisation

/control/execute visu.mac

# VERBOSE

# /control/execute verbose.mac

# WORLD GEOMETRY

/gate/world/geometry/setXLength .5 m
/gate/world/geometry/setYLength .5 m
/gate/world/geometry/setZLength 1.0 m

# PHANTOM GEOMETRY

/gate/world/daughters/name SPHERE
/gate/world/daughters/insert sphere

/gate/SPHERE/geometry/setRmin 0.
/gate/SPHERE/geometry/setRmax 75. mm
/gate/SPHERE/geometry/setPhiStart 0.
/gate/SPHERE/geometry/setDeltaPhi 2PI
/gate/SPHERE/geometry/setPThetaStart 0.
/gate/SPHERE/geometry/setDeltaTheta 2PI
/gate/SPHERE/setMaterial PMMA
/gate/SPHERE/vis/forceSolid

#=====================================================
# PHYSICS - copied from RT example 6
#=====================================================

/gate/physics/addPhysicsList QGSP_BIC #QBBC_EMY

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      Cube 1 mm
/gate/physics/Electron/SetCutInRegion   Cube 1 mm
/gate/physics/Positron/SetCutInRegion   Cube 1 mm

/gate/physics/SetMaxStepSizeInRegion world .1 mm
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon

/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter e-

# Add an Actor

#=====================================================
# Statistics actor
#=====================================================
/gate/actor/addActor                    SimulationStatisticActor stat
/gate/actor/stat/saveEveryNSeconds      120
/gate/actor/stat/save                   ../output/statistics.txt

/gate/actor/addActor

# DEFINE SOURCES

/gate/source/addSource beam
/gate/source/beam/gps/particle proton
/gate/source/beam/gps/energytype Mono
/gate/source/beam/gps/monoenergy 250 MeV

#/gate/source/beam/gps/energytype UserSpectrum
#/gate/source/beam/gps/setSpectrumFile ../data/EnergySpread.txt
#/gate/source/beam/setIntensity 1

/gate/source/beam/gps/angtype iso
/gate/source/beam/gps/mintheta 0. deg
/gate/source/beam/gps/maxtheta 0. deg
/gate/source/beam/gps/minphi 0. deg
/gate/source/beam/gps/maxphi 360. deg

/gate/source/beam/gps/type Plane
/gate/source/beam/gps/shape Circle
/gate/source/beam/gps/radius .5 cm
/gate/source/beam/gps/centre 0. 0. -25. cm


# START SIMULATION

/gate/application/setTotalNumberOfPrimaries 10000
/gate/run/initialize
/gate/application/start
