
# Visualisation

/control/execute visu.mac

# VERBOSE

/control/execute verbose.mac

# WORLD GEOMETRY

/gate/world/geometry/setXLength .5 m
/gate/world/geometry/setYLength .5 m
/gate/world/geometry/setZLength .5 m

### PHANTOM GEOMETRY

/gate/geometry/setMaterialDatabase ../data/GateMaterials.db

# Define cylinder

/gate/world/daughters/name Cylinder
/gate/world/daughters/insert cylinder
/gate/Cylinder/geometry/setRmin 0 cm
/gate/Cylinder/geometry/setRmax 3.75 cm
/gate/Cylinder/geometry/setHeight 7.5 cm
/gate/Cylinder/setMaterial Polyethylene
/gate/Cylinder/placement/setTranslation 0.0 0.0 0.0 cm
/gate/Cylinder/vis/setColor blue
/gate/Cylinder/placement/setRotationAxis 1 0 0
/gate/Cylinder/placement/setRotationAngle 90. deg

# Sample cavity

/gate/Cylinder/daughters/name cavity
/gate/Cylinder/daughters/insert cylinder
/gate/cavity/geometry/setRmin 0. cm
/gate/cavity/geometry/setRmax 1.5 cm
/gate/cavity/geometry/setHeight 5. cm
/gate/cavity/setMaterial Polyethylene
/gate/cavity/placement/setTranslation 0.0 -1.75 0.0 cm
/gate/cavity/vis/setColor red

# Sample material

/gate/cavity/daughters/name sample
/gate/cavity/daughters/insert cylinder
/gate/sample/geometry/setRmin 0. cm
/gate/sample/geometry/setRmax 1.5 cm
/gate/sample/geometry/setHeight 5. cm
/gate/sample/setMaterial Water
/gate/sample/placement/setTranslation 0.0 0.0 0.0 m
/gate/sample/vis/setColor red

/gate/sample/setMaterial Polyethylene
/gate/sample/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sample/vis/setColor white

# Define film

/gate/Cylinder/daughters/name Film
/gate/Cylinder/daughters/insert box
/gate/Film/geometry/setXLength 3. cm
/gate/Film/geometry/setYLength 3. cm
/gate/Film/geometry/setZLength .278 mm
/gate/Film/setMaterial EBT-3-Polyester
/gate/Film/placement/setTranslation 0.0 +1.75 0.0 cm
/gate/Film/vis/setColor yellow
/gate/Film/placement/setRotationAxis 0 1 0
/gate/Film/placement/setRotationAngle 3. deg

# Define active region

/gate/Film/daughters/name Active_layer
/gate/Film/daughters/insert box
/gate/Active_layer/geometry/setXLength 3. cm
/gate/Active_layer/geometry/setYLength 3. cm
/gate/Active_layer/geometry/setZLength  .028 mm
/gate/Active_layer/setMaterial EBT-3-Active
/gate/Active_layer/placement/setTranslation 0.0 0.0 0.0 cm
/gate/Active_layer/vis/setColor blue


#/vis/viewer/update
/gate/geometry/rebuild

#=====================================================
# PHYSICS - copied from RT example 6
#=====================================================

/gate/physics/addPhysicsList emlivermore #QGSP_BIC #QBBC_EMY

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      Cylinder 10 mm
/gate/physics/Electron/SetCutInRegion   Cylinder 10 mm
/gate/physics/Positron/SetCutInRegion   Cylinder 10 mm

# /gate/physics/Gamma SetCutInRegion Film

/gate/physics/SetMaxStepSizeInRegion world .1 mm
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon

/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter e-

# Add an Actor

#=====================================================
# Statistics actor
#=====================================================
/gate/actor/addActor                    SimulationStatisticActor stat
/gate/actor/stat/saveEveryNSeconds      120
/gate/actor/stat/save                   ../output/statistics.txt


#/gate/output/allowNoOutput

/gate/actor/addActor DoseActor FilmDose

/gate/actor/FilmDose/save                          /media/sf_Desktop/film/film-test-normal-materials-3deg_tilt-5mmActive.txt

/gate/actor/FilmDose/attachTo Active_layer
/gate/actor/FilmDose/setPosition                   0. 0. 0. cm
#/gate/actor/FilmDose/setSize 40 50 0.028 mm
#/gate/actor/FilmDose/setVoxelSize 0.5 0.5 0.028 mm
/gate/actor/FilmDose/stepHitType random
/gate/actor/FilmDose/setResolution 1 300 1
/gate/actor/FilmDose/enableDose                    true
/gate/actor/FilmDose/enableDoseToWater             false
/gate/actor/FilmDose/enableEdep                    true
/gate/actor/FilmDose/enableNumberOfHits            true

/gate/actor/FilmDose/saveEveryNSeconds             60

# DEFINE SOURCES

/gate/source/addSource beam
/gate/source/beam/gps/particle proton
/gate/source/beam/gps/energytype Mono
/gate/source/beam/gps/monoenergy 90 MeV

#/gate/source/beam/gps/energytype UserSpectrum
#/gate/source/beam/gps/setSpectrumFile ../data/EnergySpread.txt
#/gate/source/beam/setIntensity 1

/gate/source/beam/gps/angtype iso
/gate/source/beam/gps/mintheta 0. deg
/gate/source/beam/gps/maxtheta 0. deg
/gate/source/beam/gps/minphi 0. deg
/gate/source/beam/gps/maxphi 360. deg

/gate/source/beam/gps/type Plane
/gate/source/beam/gps/shape Circle
/gate/source/beam/gps/radius .5 cm
/gate/source/beam/gps/centre 0. 0. -15. cm


# START SIMULATION

/gate/application/setTotalNumberOfPrimaries 100000
/gate/run/initialize
/gate/application/start
