#=====================================================
# PHYSICS - copied from RT example 6
#=====================================================

/gate/physics/addPhysicsList QBBC

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/SetMaxStepSizeInRegion world .1 mm
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon

/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter e-

# DOSE ACTOR

/gate/actor/addActor DoseActor Range

/gate/actor/Range/attachTo Film
/gate/actor/Range/setPosition                   0. 0. 0. cm
/gate/actor/Range/stepHitType random
/gate/actor/Range/setResolution 120 160 1
/gate/actor/Range/enableDose                    true
/gate/actor/Range/enableDoseToWater             true
/gate/actor/Range/enableEdep                    true
/gate/actor/Range/enableNumberOfHits            true
/gate/actor/Range/save ../results/phantom-80MeV-5cm-beam-defaultMaterials.txt
#/gate/actor/Range/save ../results/film-test-80MeV-cylinders.mhd

/gate/actor/Range/saveEveryNSeconds             60

# DEFINE SOURCES

/gate/source/addSource beam
/gate/source/beam/gps/particle proton
/gate/source/beam/gps/energytype Gauss
/gate/source/beam/gps/energy 80 MeV
/gate/source/beam/gps/sigmae 2.355 MeV

/gate/source/beam/gps/angtype iso
/gate/source/beam/gps/mintheta 90. deg
/gate/source/beam/gps/maxtheta 90. deg
/gate/source/beam/gps/minphi 0. deg
/gate/source/beam/gps/maxphi 0. deg

/gate/source/beam/gps/type Plane
/gate/source/beam/gps/shape Circle
/gate/source/beam/gps/radius 2.5 cm

/gate/source/beam/gps/centre 15. 0. 0 cm
