#/control/execute visu0.mac
/control/execute verbose.mac

/control/execute volume_box.mac
/control/execute physics_box.mac
/control/execute source_3.mac

#/gate/actor/addActor SimulationStatisticActor Stats
#/gate/actor/Stats/saveEveryNSeconds             60
#/gate/actor/Stats/save  /media/sf_linux_share/Data/GATE_Simulations/wedge/Stats.txt

/gate/actor/film2/save /media/sf_linux_share/Data/GATE_Simulations/wedge/validation/validation_box_source_3.txt


/gate/application/setTotalNumberOfPrimaries 1000000
/gate/output/allowNoOutput
/gate/run/initialize
/gate/application/start
