# WORLD GEOMETRY

/gate/world/geometry/setXLength .5 m
/gate/world/geometry/setYLength .5 m
/gate/world/geometry/setZLength .5 m

### PHANTOM GEOMETRY

/gate/geometry/setMaterialDatabase /media/sf_linux_share/code/Gate/phantom_v4/data/GateMaterials.db

# Define Phantom

# Phantom

/gate/world/daughters/name Phantom
/gate/world/daughters/insert box
/gate/Phantom/geometry/setXLength 10. cm
/gate/Phantom/geometry/setYLength 10. cm
/gate/Phantom/geometry/setZLength 10. cm
/gate/Phantom/placement/setTranslation 0.0 0.0 0.0 cm
/gate/Phantom/setMaterial Water # Polyethylene
/gate/Phantom/vis/setColor blue

#/gate/geometry/setIonisationPotential Polyethylene #75 eV

# Film

/gate/Phantom/daughters/name film2
/gate/Phantom/daughters/insert box
/gate/film2/geometry/setXLength 35 mm
/gate/film2/geometry/setYLength 60 mm
/gate/film2/geometry/setZLength 20 mm
/gate/film2/placement/setTranslation -12.5 0  . mm
/gate/film2/setMaterial Water # EBT-3-Polyester
/gate/film2/placement/setRotationAxis 0 1 0
/gate/film2/placement/setRotationAngle +1 deg

# Insert 1 - Lung

/gate/Phantom/daughters/name Lung
/gate/Phantom/daughters/insert box
/gate/Lung/geometry/setXLength 15 mm
/gate/Lung/geometry/setYLength 15 mm
/gate/Lung/geometry/setZLength 15 mm
/gate/Lung/placement/setTranslation 1.75 -1.6 0. cm
/gate/Lung/setMaterial LN10
/gate/Lung/vis/setColor red

# Insert 2 - Bone

/gate/Phantom/daughters/name Bone
/gate/Phantom/daughters/insert box
/gate/Bone/geometry/setXLength 15 mm
/gate/Bone/geometry/setYLength 15 mm
/gate/Bone/geometry/setZLength 15 mm
/gate/Bone/placement/setTranslation 1.75 1.6 0. cm
/gate/Bone/setMaterial SB5
/gate/Bone/vis/setColor white

/gate/geometry/rebuild
