/control/execute visu0.mac
/control/execute verbose.mac

/control/execute volumes.mac
/control/execute physics.mac

/gate/actor/addActor SimulationStatisticActor Stats
/gate/actor/Stats/saveEveryNSeconds             60
/gate/actor/Stats/save  /media/sf_linux_share/Data/GATE_Simulations/wedge/Stats.txt

/gate/actor/film1/save /media/sf_linux_share/Data/GATE_Simulations/wedge/film1_beam_from_front.txt
/gate/actor/film2/save /media/sf_linux_share/Data/GATE_Simulations/wedge/film2_beam_from_front.txt
/gate/actor/film3/save /media/sf_linux_share/Data/GATE_Simulations/wedge/film3_beam_from_front.txt

/gate/application/setTotalNumberOfPrimaries 100000
/gate/output/allowNoOutput
/gate/run/initialize
/gate/application/start
